# Generated by Django 4.2.28 on 2026-02-06 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('history', models.TextField(blank=True)),
                ('materials', models.TextField(blank=True)),
                ('playing_technique', models.TextField(blank=True)),
                ('cultural_significance', models.TextField(blank=True)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='instruments/images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('model_3d', '3D Model'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to='instruments/media/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.instrument')),
            ],
            options={
                'ordering': ['media_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('expertise', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('detailed_bio', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='experts/photos/')),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('performance_video', models.FileField(blank=True, null=True, upload_to='experts/videos/')),
                ('teaching_audio', models.FileField(blank=True, null=True, upload_to='experts/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instruments', models.ManyToManyField(blank=True, related_name='experts', to='catalog.instrument')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
